using FAPP.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FAPP.Areas.AM.FormsBLL
{
    public class AMFormsBLL
    {
        public static void InsertAMForms(OneDbContext c_db, int applicationmoduleId, ref string Error, ref string Message)
        {
            try
            {
                if (applicationmoduleId == 1603)
                {
                    c_db.Database.ExecuteSqlCommand($@"DELETE FROM [System].[Forms] WHERE [ApplicationModuleId] = {applicationmoduleId} ");
                    c_db.Database.ExecuteSqlCommand($@"

                     
 INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300001, N'/AM/Dashboard/Index', N'Dashboard', N'Dashboard',            1, N'', 1, 0, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 1, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300002, N'/AM/Requests', N'Requests', N'Requests',                     1, N'', 1, 3, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300003, N'/AM/Issue', N'Issuance', N'Issuance',                        1, N'', 1, 5, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300004, N'/AM/Issue/ItemPosition', N'Item Register', N'Item Register', 1, N'', 1, 6, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300005, N'/AM/Depreciation/Manage', N'Depreciation', N'Depreciation',  1, N'', 1, 6, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, N'', N'Home', N'InsertMembershipFormsWithStaticFormId', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300006, N'/AM/Reports', N'Reports', N'Reports',                        1, N'', 1, 6, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, N'', N'Home', N'InsertMembershipFormsWithStaticFormId', 0, 1, 0, 0, 0, NULL, 1603)

                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300007, N'/AM/Issue/Index', N'Dashboard', N'Dashboard',                         160300002, N'', 1, 0, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 1, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300008, N'/AM/Requests/AddEditRequest', N'New Request', N'New Request',         160300002, N'', 0, 1, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300009, N'/AM/Requests/ManageRequests', N'Manage Requests', N'Manage Requests', 160300002, N'', 1, 2, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)

                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300010, N'/AM/Issue/Index', N'Dashboard', N'Dashboard',                                             160300003, N'', 1, 0, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 1, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300011, N'/AM/Issue/IssueItems', N'Issuance / Return / Damage', N'Issuance / Return / Damage',      160300003, N'', 1, 1, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300012, N'/AM/Issue/ManageIssuedItems', N'Manage Issued Vouchers', N'Manage Issued Vouchers',       160300003, N'', 1, 2, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'No', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300013, N'/AM/ReturnIssue/ReturnIssuedItems', N'Manage Return Vouchers', N'Manage Return Vouchers', 160300003, N'', 1, 4, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'No', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300014, N'/AM/ReturnIssue/AddEditReturnIssue', N'New Return Voucher', N'New Return Voucher',        160300003, N'', 0, 3, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'No', 1, 3, N'', N'', 0, N'', N'', N'', N'', 0, N'', 0, 0, N'', N'', 0, 0, N'', N'glyphicon-ok', N'', N'', N'', N'', N'', 0, 0, 0, 0, 0, NULL, 1603)

                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300015, N'/AM/Reports/Index', N'Dashboard', N'Dashboard',      160300006, N'', 1, 1, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, N'', N'Home', N'InsertMembershipFormsWithStaticFormId', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300016, N'/AM/Reports/Issuance', N'Issuance', N'Issuance',     160300006, N'', 1, 6, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, N'', N'Home', N'InsertMembershipFormsWithStaticFormId', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300017, N'/AM/Reports/Damages', N'Damages', N'Damages',        160300006, N'', 1, 6, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, N'', N'Home', N'InsertMembershipFormsWithStaticFormId', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300018, N'/AM/Reports/AssetLog', N'Assets Log', N'Assets Log', 160300006, N'', 1, 6, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, N'', N'Home', N'InsertMembershipFormsWithStaticFormId', 0, 0, 0, 0, 0, NULL, 1603)
                         INSERT[System].[Forms]([FormID], [FormURL], [MenuText], [FormName], [ParentForm], [PageType], [IsMenuItem], [MenuItemPriority], [Icon], [isActive], [ShowOnDesktop], [ModuleId], [Target], [Slug], [ModifiedBy], [IP], [DefaultReportFileName], [PageDescription], [HelpURL], [Depth], [Lineage], [IsQuickLink], [NewFeature], [NewFeatureTitle], [ControllerName], [IsDashboardPart], [IsMasterMenu], [DefaultParameter], [FaIcon], [Section], [Module], [Area], [Controller], [Action], [IsGroupReportHead], [IsHideChilds], [IsAjaxRequest], [IsAction], [IsReport], [OtherName], [ApplicationModuleId]) VALUES(160300019, N'/AM/Reports/Summary', N'Summary', N'Summary',        160300006, N'', 1, 6, N'<img src=''https://maxcdn.icons8.com/Color/PNG/48/Programming/administrative_tools-48.png'' width=''48'' height=''48''>', N'Yes', 1, 3, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, N'', N'Home', N'InsertMembershipFormsWithStaticFormId', 0, 0, 0, 0, 0, NULL, 1603)
     



                ");
                    c_db.Database.ExecuteSqlCommand($@"INSERT INTO [System].[FormGroupRights]
                           ([UserGroupId]
                           ,[FormId]
                           ,[Allowed])
                SELECT usrGrp.UserGroupId
                , frm.FormID
                , 1
                FROM [System].Forms frm
                CROSS JOIN [Membership].UserGroups usrGrp
                LEFT JOIN [System].[FormGroupRights] frmGrpRt ON frmGrpRt.FormId = frm.FormID
	                AND frmGrpRt.UserGroupId = usrGrp.UserGroupId
                WHERE frmGrpRt.FormId is NULL");
                }
                Message += "Finance forms updated successfully.\n";
            }
            catch (Exception ex)
            {
                Error += "Finance Forms Updation Error: '" + ex.GetExceptionMessages() + "'\n";
            }
        }
    }
}