using FAPP.Model;
using System.Collections.Generic;

namespace FAPP.Areas.AM.ViewModels.PrimaryData
{
    public partial class MenuLinks
    {
        public List<Form> GetDairyFarmMenuLinks()
        {


            return new List<Form>() {
                new Form { FormID = 18001, FormName = "Dairy Farm", FormURL = "/DairyFarm/Dashboard/", ParentForm = 1, IsMenuItem = true, MenuText = "Dairy Farm", MenuItemPriority = 201, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "DairyFarm", Controller = "Dashboard", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
                new Form { FormID = 1800100, FormName = "Dashboard", FormURL = "/DairyFarm/Dashboard/Index", ParentForm = 18001, IsMenuItem = false, MenuText = "Dashboard", MenuItemPriority = 0, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "DiaryFarm", Controller = "Dashboard", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800101, FormName = "Setup", FormURL = "/DairyFarm/Setup/", ParentForm = 18001, IsMenuItem = false, MenuText = "Setup", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "DiaryFarm", Controller = "Setup", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800102, FormName = "Purchase", FormURL = "/DairyFarm/Purchase/Manage", ParentForm = 18001, IsMenuItem = false, MenuText = "Purchase", MenuItemPriority = 2, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Manage", Area = "DiaryFarm", Controller = "Purchase", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800103, FormName = "Sales", FormURL = "/DairyFarm/Sales/Manage", ParentForm = 18001, IsMenuItem = false, MenuText = "Sales", MenuItemPriority = 3, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Manage", Area = "DiaryFarm", Controller = "Sales", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800104, FormName = "Animals List", FormURL = "/DairyFarm/Stocks/Manage", ParentForm = 18001, IsMenuItem = false, MenuText = "Animals List", MenuItemPriority = 4, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Manage", Area = "DiaryFarm", Controller = "Stocks", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800105, FormName = "Milk Production", FormURL = "/DairyFarm/MilkProduction/Manage", ParentForm = 18001, IsMenuItem = false, MenuText = "Milk Production", MenuItemPriority = 5, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Manage", Area = "DiaryFarm", Controller = "MilkProduction", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800106, FormName = "Animal Weights", FormURL = "/DairyFarm/WeightReadings/Manage", ParentForm = 18001, IsMenuItem = false, MenuText = "Animal Weights", MenuItemPriority = 6, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Manage", Area = "DiaryFarm", Controller = "WeightReadings", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800107, FormName = "Cow Servicing", FormURL = "/DairyFarm/AnimalServicing/Manage", ParentForm = 18001, IsMenuItem = false, MenuText = "Cow Servicing", MenuItemPriority = 7, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Manage", Area = "DiaryFarm", Controller = "AnimalServicing", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800108, FormName = "Semens", FormURL = "/DairyFarm/Semens/Manage", ParentForm = 18001, IsMenuItem = false, MenuText = "Semens", MenuItemPriority = 8, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Manage", Area = "DiaryFarm", Controller = "Semens", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800109, FormName = "Pregnency Record", FormURL = "/DairyFarm/PregnancyRecords/ManagePregnancyRecords", ParentForm = 18001, IsMenuItem = false, MenuText = "Pregnancy Record", MenuItemPriority = 2, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "ManagePregnancyRecords", Area = "DiaryFarm", Controller = "PregnancyRecords", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 1800110, FormName = "Lactation", FormURL = "/DairyFarm/lactations/Manage", ParentForm = 18001, IsMenuItem = false, MenuText = "Lactation", MenuItemPriority = 2, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Manage", Area = "DiaryFarm", Controller = "lactations", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 180010100, FormName = "Dashboard", FormURL = "/DairyFarm/Setup/Index", ParentForm = 1800101, IsMenuItem = false, MenuText = "Dashboard", MenuItemPriority = 0, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "DiaryFarm", Controller = "Setup", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 180010101, FormName = "Animal Types", FormURL = "/DairyFarm/Setup/AnimalTypes", ParentForm = 1800101, IsMenuItem = false, MenuText = "Animal Types", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "AnimalTypes", Area = "DiaryFarm", Controller = "Setup", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 180010102, FormName = "Animal Breed", FormURL = "/DairyFarm/Setup/AnimalBreeds", ParentForm = 1800101, IsMenuItem = false, MenuText = "Animal Breed", MenuItemPriority = 2, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "AnimalBreeds", Area = "DiaryFarm", Controller = "Setup", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
new Form { FormID = 180010103, FormName = "Growth Stages", FormURL = "/DairyFarm/Setup/GrowthStages", ParentForm = 1800101, IsMenuItem = false, MenuText = "Growth Stages", MenuItemPriority = 2, isActive = "Yes", ShowOnDesktop = true, ModuleId = 201, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "GrowthStages", Area = "DiaryFarm", Controller = "Setup", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/doodle/60/000000/books.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },


            };
        }
    }
}