using FAPP.Model;
using System.Collections.Generic;

namespace FAPP.Areas.AM.ViewModels.PrimaryData
{
    public partial class MenuLinks
    {
        public List<Form> GetIBMenulinks()
        {
            return new List<Form>()
            {

                new Model.Form { FormID = 2011120705, FormName = "IB", FormURL = "/IB/Dashboard", ParentForm = 1, IsMenuItem = true, MenuText = "IB", MenuItemPriority = 2, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
                new Model.Form { FormID = 2011120723, FormName = "Fee", FormURL = "/IB/Fee/Fee", ParentForm = 2011120705, IsMenuItem = false, MenuText = "Fee", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
                new Model.Form { FormID = 2011120706, FormName = "E-Learning", FormURL = "/IB/ELearning/ELearning", ParentForm = 2011120705, IsMenuItem = false, MenuText = "E-Learning", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
                new Model.Form { FormID = 2011120707, FormName = "Events", FormURL = "/IB/Events/Index", ParentForm = 2011120706, IsMenuItem = false, MenuText = "Events", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                new Model.Form { FormID = 2011120724, FormName = "Reports", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120723, IsMenuItem = false, MenuText = "Reports", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                new Model.Form { FormID = 2011120708, FormName = "Activity Calendar", FormURL = "/IB/Activities/Calendar", ParentForm = 2011120706, IsMenuItem = false, MenuText = "Activity Calendar", MenuItemPriority = 10, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Calendar", Area = "IB", Controller = "Activities", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/day-view.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                new Model.Form { FormID = 2011120709, FormName = "Resources", FormURL = "/IB/Resources/Index", ParentForm = 2011120706, IsMenuItem = false, MenuText = "Resources", MenuItemPriority = 14, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Resources", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/google-sites.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                new Model.Form { FormID = 2011120710, FormName = "Dashboard", FormURL = "/IB/TeachersAndTimeTables/Index", ParentForm = 2011120706, IsMenuItem = false, MenuText = "Dashboard", MenuItemPriority = 0, isActive = "Yes", ShowOnDesktop = true, ModuleId = 0, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "TeachersAndTimeTables", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/classroom.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                //IBAcademic
                 new Model.Form { FormID = 2011120725, FormName = "Academics", FormURL = "/Academics/Dashboard/Index", ParentForm = 2011120705, IsMenuItem = false, MenuText = "Academics", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
                            new Model.Form { FormID = 2011120726, FormName = "Exam & Results", FormURL = "/FrontDesk/Purchase", ParentForm = 2011120725, IsMenuItem = false, MenuText = "Exam & Results", MenuItemPriority = 3, isActive = "Yes", ShowOnDesktop = true, ModuleId = 11, Target = "", Slug = "", PageType = "HaveChilds", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "Setup", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/shopping-cart/nolan/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },


new Model.Form { FormID = 2011120727, FormName = "Setup", FormURL = "/Academics/Dashboard/Index", ParentForm = 2011120726, IsMenuItem = false, MenuText = "Setup", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "HaveChilds", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "Setup", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
                new Model.Form { FormID = 2011120729, FormName = "Grading", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120727, IsMenuItem = false, MenuText = "Grading", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "HaveChilds", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                       new Model.Form { FormID = 2011120732, FormName = "Grades", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120729, IsMenuItem = false, MenuText = "Grades", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                       new Model.Form { FormID = 2011120733, FormName = "Class Wise Grading Schemes", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120729, IsMenuItem = false, MenuText = "Class Wise Grading Schemes", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                                    new Model.Form { FormID = 2011120734, FormName = "Subject Wise Grading Schemes", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120729, IsMenuItem = false, MenuText = "Subject Wise Grading Schemes", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },

                                new Model.Form { FormID = 2011120730, FormName = "Evalaution", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120727, IsMenuItem = false, MenuText = "Evalaution", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "HaveChilds", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                                       new Model.Form { FormID = 2011120735, FormName = "Evalaution Fields", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120730, IsMenuItem = false, MenuText = "Evalaution Fields", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                                        new Model.Form { FormID = 2011120736, FormName = "Evaluation Grades", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120730, IsMenuItem = false, MenuText = "Evaluation Grades", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },


                                                new Model.Form { FormID = 2011120731, FormName = "Subject Management", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120727, IsMenuItem = false, MenuText = "Subject Management", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "HaveChilds", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                                                new Model.Form { FormID = 2011120737, FormName = "Subjects", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120731, IsMenuItem = false, MenuText = "Subjects", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },
                                                new Model.Form { FormID = 2011120738, FormName = "Sub Subjects", FormURL = "/IB/IBFeeReport/Receipts", ParentForm = 2011120731, IsMenuItem = false, MenuText = "Sub Subjects", MenuItemPriority = 9, isActive = "Yes", ShowOnDesktop = false, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "Index", Area = "IB", Controller = "Events", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "https://png.icons8.com/color/60/000000/overtime.png", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = true, Lineage = "", ModifiedBy = 0, Module = "IB", NewFeature = false, NewFeatureTitle = "", Section = "IB", },

new Model.Form { FormID = 2011120728, FormName = "Reports", FormURL = "/Academics/Dashboard/Index", ParentForm = 2011120726, IsMenuItem = false, MenuText = "Reports", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },

  new Model.Form { FormID = 2011120739, FormName = "Human Resources", FormURL = "/HRPayroll/Dashboard", ParentForm = 2011120705, IsMenuItem = false, MenuText = "Human Resources", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },

    new Model.Form { FormID = 2011120740, FormName = "Finance", FormURL = "/Finance/Dashboard/Index", ParentForm = 2011120705, IsMenuItem = false, MenuText = "Finance", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },

      new Model.Form { FormID = 2011120741, FormName = "Setup", FormURL = "/Setup/Dashboard", ParentForm = 2011120705, IsMenuItem = false, MenuText = "Setup", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },

            new Model.Form { FormID = 2011120742, FormName = "Contacts", FormURL = "/Setup/Dashboard", ParentForm = 2011120705, IsMenuItem = false, MenuText = "Contacts", MenuItemPriority = 1, isActive = "Yes", ShowOnDesktop = true, ModuleId = 41, Target = "", Slug = "", PageType = "", PageDescription = "", Action = "", Area = "", Controller = "", ControllerName = "", DefaultParameter = "", DefaultReportFileName = "", Depth = 0, FaIcon = "", HelpURL = "", Icon = "<img src='https://png.icons8.com/receipt/dusk/64' width='48' height='48'>", IP = "", IsAction = false, IsAjaxRequest = false, IsDashboardPart = false, IsGroupReportHead = false, IsHideChilds = false, IsQuickLink = false, Lineage = "", ModifiedBy = 0, Module = "", NewFeature = false, NewFeatureTitle = "", Section = "", },
            };
        }
    }
}