//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAPP.Classes.Messaging.DTOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v__Defaulters
    {
        public string RegistrationNumber { get; set; }
        public string Name { get; set; }
        public string SessionName { get; set; }
        public string Clasec { get; set; }
        public string GroupName { get; set; }
        public string FatherMobile { get; set; }
        public decimal PrevBalance { get; set; }
        public decimal CurrBalance { get; set; }
        public System.Guid SessionId { get; set; }
        public System.Guid ClassId { get; set; }
        public System.Guid SectionId { get; set; }
        public int StudentId { get; set; }
        public bool Active { get; set; }
        public string FatherName { get; set; }
        public Nullable<decimal> NetBalance { get; set; }
        public string GRNo { get; set; }
    }
}
