//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAPP.Classes.Messaging.DTOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v__FeeReceipts
    {
        public long FeeVoucherId { get; set; }
        public short PaymentModeId { get; set; }
        public string ChequeNumber { get; set; }
        public string AccountId { get; set; }
        public string PaymentModeName { get; set; }
        public string Name { get; set; }
        public string GroupName { get; set; }
        public string RegistrationNo { get; set; }
        public string AccountTitle { get; set; }
        public long FeeReceiptId { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string GRNo { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.Guid ClassId { get; set; }
        public System.Guid SectionId { get; set; }
        public Nullable<short> ClassOrder { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<short> BranchId { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public string VoucherDuration { get; set; }
        public string FatherName { get; set; }
        public string FullName { get; set; }
    }
}
