//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAPP.Classes.Messaging.DTOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v__PTM
    {
        public int TeacherId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string RoomName { get; set; }
        public string ClassName { get; set; }
        public int StudentId { get; set; }
    }
}
