//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAPP.Classes.Messaging.DTOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v__VoucherDetails
    {
        public long FeeVoucherId { get; set; }
        public int StudentId { get; set; }
        public string NAME { get; set; }
        public string SessionName { get; set; }
        public string SectionName { get; set; }
        public string ClassName { get; set; }
        public System.DateTime DueDate { get; set; }
        public string DefaultStatus { get; set; }
        public System.Guid SessionId { get; set; }
        public System.Guid ClassId { get; set; }
        public System.Guid SectionId { get; set; }
        public string Clasec { get; set; }
        public string GroupName { get; set; }
        public System.DateTime IssueDate { get; set; }
        public decimal Amount { get; set; }
        public decimal Fine { get; set; }
        public decimal Discount { get; set; }
        public decimal PaidAmount { get; set; }
        public string VoucherStatus { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public short BranchId { get; set; }
        public System.DateTime FeeMonth { get; set; }
        public string Duration { get; set; }
        public string RegistrationNumber { get; set; }
        public string FatherName { get; set; }
    }
}
